### ISSUE TITLE
The plugin can't support Synchronized scrolling

### ISSUE THREAD

**Issue by cposture** [MikeCoder/markdown-preview.vim#1]
I have a good idea that the content in vim and webpage can  Synchronizely scrolling, just like a advanced markdown editor Mou in mac.
I hope you can add the new feature to the next version.
Thanks in advance!

**Comment by D0n9X1n** [comment]
The new version will release in 2 days. and you will see the feature.

**Comment by D0n9X1n** [comment]
see the [ReadMe](https://github.com/MikeCoder/markdown-preview.vim/blob/master/README.md) and find the live preview part

**Comment by cposture** [comment]
well done,thanks
