### ISSUE TITLE
Support for "python/dyn" and not just "python"

### ISSUE THREAD

**Issue by chris2fr** [MikeCoder/markdown-preview.vim#16]
## Expected Behavior 

Default Windows installers use "python/dyn" and not "python" as compile options. This works with other plugins and should also work with this markdown-preview. 

`: version` will have both `+python/dyn` and `+python3/dyn` but no trace of `python` nor `python3` (if not prefixes of `-`). 

The plugin should load and work.

## Actual Behavior

The plugin doesn't load because of a requirement for `python`

**Comment by chris2fr** [comment]
I had 32-bit Vim on my windows machine without 32bit Python. Resolution was to install 64-bit Vim.

**Comment by D0n9X1n** [comment]
Cool~

**Comment by D0n9X1n** [comment]
Could you help me to check the previous ISSUE #15  fixed?

I believe you can just update this plugin by `:PlugUpdate` or other similiar commands.
