### ISSUE TITLE
Windows QA

### ISSUE THREAD

**Issue by chris2fr** [MikeCoder/markdown-preview.vim#17]
## Expected Behavior 

Full Testing under Windows allows plugin to start without warning of Windows discouragement.

## Actual Behavior

Message shows warning about Windows discouragement.

## Specifications

What does constitute testing of this plugin?  
What different Windows configurations can we anticipate? (32bit/64bit mismatches for example with Python, requirements, etc.)  
May we hold hands of Windows users?

**Comment by D0n9X1n** [comment]
Well, on Windows, there are too many environments vim could be in, like Cygwin, MinGW, WSL, WSL2 .etc. 
Compatibility testing might takes too much effort and it is impossible for one man to follow...

So, I decide not to support this on Windows. I can remove that warning or you can do that yourself, but I don't guarantee this could work 100% on Windows.

Any contribution is acceptable and welcome. 👍

**Comment by chris2fr** [comment]
Compatibility testing [...] is impossible.
Any contribution is acceptable.

OK, I will see what I can do. I think this is more a theoretical proof than a practical testing.

Let Vim always be able to use "/" instead of "\" 
Let ....

With enough assumptions, I think we can be reasonably sure that it would work with Windows.

After the proof, let's change the name. There are too many markdown-preview. I would propose markdown-file-preview because the main value of this plugin, compared to others, is its use of a file and not a TCP port.
