### ISSUE TITLE
Do not work in the vim of Ubuntu16.04

### ISSUE THREAD

**Issue by maywanting** [MikeCoder/markdown-preview.vim#6]
I had added this plugin in my vim. But when I attempted to use it, can not find the `MarkdownPreview` command. I checked my vim setting, all the settings is OK and the plugin is existed in the bundle directory.

Then I found the vim in Ubuntu16.04 using python3 rather than python2, and this plugin maybe written by python2. So installing the package named `vim-nox-py2` will work for this problem.

Just a suggestion, making another branch to support python3 will be fine :)

**Comment by D0n9X1n** [comment]
After 22 days, I have fixed the bug.

Update to the latest version, and enjoy your writing with markdown.
