### ISSUE TITLE
Plugin doesn't work with Plug

### ISSUE THREAD

**Issue by rscircus** [MikeCoder/markdown-preview.vim#8]
Although I'm happy about this plugin's nice features this plugin doesn't work with [Plug](https://github.com/junegunn/vim-plug).

The reason are the hardcoded `bundle` paths in:

```
plugin/markdown-preview.vim
35:    let g:SourceMarkDownCssDir='~/.vim/bundle/markdown-preview.vim/resources'

pythonx/markdown_init.py
26:            SourceResDir = os.path.join(vim.eval('$HOME'), '.vim', 'bundle/markdown-preview.vim/resources')
28:            SourceResDir = os.path.join(vim.eval('$HOME'), '.nvim', 'bundle/markdown-preview.vim/resources')
30:            SourceResDir = os.path.join(vim.eval('$HOME'), '.vim', 'bundle/markdown-preview.vim/resources')

deploy.sh
6:mv ~/.vim/bundle/markdown-preview.vim ~/markdown-preview.vim.back
7:cp -r ../markdown-preview.vim ~/.vim/bundle/markdown-preview.vim
```
If there is need, I'd contribute to a solution. :blush:

**Comment by D0n9X1n** [comment]
Nice! Any PR is acceptable.

**Comment by sadid** [comment]
I think I have exactly same problem (with both vim and neovim):


```
Error detected while processing function MarkdownPreviewInit[5]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/sadid/.local/share/nvim/plugged/markdown-preview.vim/pythonx/markdown_init.py", line 37, in init
    shutil.copytree(SourceResDir, DisResDir)
  File "/usr/lib/python3.6/shutil.py", line 309, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sadid/.nvim/bundle/markdown-preview.vim/resources'
Press ENTER or type command to continue
```

**Comment by D0n9X1n** [comment]
You can copy the folder `/home/sadid/.local/share/nvim/plugged/markdown-preview.vim/resources` to `~/.nvim/MarkDownRes` and add a empty file with name '3.0.3' to avoid this situation. By following these steps:
```
cp -r /home/sadid/.local/share/nvim/plugged/markdown-preview.vim/resources ~/.nvim/MarkDownRes
cd ~/.nvim/MarkDownRes
touch 3.0.3
```
I will try to solve this problem. Thanks for giving the case.

**Comment by D0n9X1n** [comment]
Or you can see [here](https://github.com/MikeCoder/markdown-preview.vim#config).

+ Using `PlugUpdate` to upgrade to version 3.1.0
+ Add the following code into your vimrc file.
```
" markdown-preview.vim {{{
    let g:PluginDir = '/home/sadid/.local/share/nvim/plugged/markdown-preview.vim/'
" }}}

```

**Comment by sadid** [comment]
Thanks, 
I've tested both approaches but unfortunately I couldn't solve the problem. Regarding neovim I tried different scenarios such as creating `.nvim` as your example. Creating similar directory in `.local/share/nvim`, etc.
