### ISSUE TITLE
Idea: Synchronized Scrolling

### ISSUE THREAD

**Issue by rscircus** [MikeCoder/markdown-preview.vim#9]
I would really like a synchronized scrolling feature, like SyncTex allows for LaTeX Editors.

Any body interested in that? :blush:

**Comment by D0n9X1n** [comment]
[Earlier](https://github.com/MikeCoder/markdown-preview.vim/releases/tag/2.1.0) I wrote this feature(Based on Ajax), but I found that I didn't use it much and its performance was not good. So, I delete this feature. Maybe someone could have a better solution(for example based on websock).  Any contribution is acceptable and welcome. 👍
